services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - exist
    # ports:
      # - "8080:8080"
    environment:
      SEARXNG_BASE_URL: "http://searxng:8080"
      INSTANCE_NAME: "Existential SearxNG"
      REDIS_URL:
      CC_PASSWORD:
      CC_USER:
      SEARCH_ENGINE_TIMEOUT: 2.0
      AUTOCOMPLETE: "true"
      USE_HTTPS: "false"
      SEARXNG_SETTINGS_PATH: "/etc/searxng/settings.yml"
      MORTY_SECRET:
      MORTY_URL:
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:Z

networks:
  exist:
    external: true
